name: agropath
description: "A pbl 3rd semester project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2
  firebase_storage: ^12.3.5
  image_picker: ^1.0.0
  http: ^1.2.2
  flutter_shopping_cart: ^1.0.1
  intl: ^0.19.0
  weather: ^3.0.0
  geolocator: ^13.0.2
  provider: ^6.1.2
  geocoding: ^3.0.0
  shared_preferences: ^2.3.3
  flutter_launcher_icons: "^0.14.1"  # Make sure you use the latest version available

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  

flutter:
  uses-material-design: true
  assets:
    - assets/logo/agropath.png
    - assets/logo/
  fonts:
    - family: ProtestStrike
      fonts:
        - asset: assets/fonts/ProtestStrike.ttf

flutter_icons:
  android: true  # This generates the icon for Android
  ios: true  # This generates the icon for iOS
  image_path: "assets/favicon/agropath.png"  # Correct path to your app's icon image
  min_sdk_android: 21  # Minimum SDK version for Android (optional)
  web:
    generate: true
    image_path: "assets/favicon/agropath.png"  # Path for web icon (optional)
    background_color: "#ffffff"  # Background color for web (optional)
  windows:
    generate: true
    image_path: "assets/favicon/agropath.png"  # Path for Windows icon (optional)
    icon_size: 48  # Icon size for Windows (optional)
  macos:
    generate: true
    image_path: "assets/favicon/agropath.png"  # Path for macOS icon (optional)
